-- AlterTable
ALTER TABLE "sections" ADD COLUMN     "bgImageOpacity" INTEGER DEFAULT 100,
ADD COLUMN     "bgImagePosition" TEXT DEFAULT 'center',
ADD COLUMN     "bgImageRepeat" TEXT DEFAULT 'no-repeat',
ADD COLUMN     "bgImageSize" TEXT DEFAULT 'cover',
ADD COLUMN     "bgImageUrl" TEXT,
ADD COLUMN     "bgParallax" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hoverAlwaysShow" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hoverAnimateBehind" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hoverAnimationType" TEXT DEFAULT 'slide',
ADD COLUMN     "hoverFontFamily" TEXT DEFAULT 'Arial',
ADD COLUMN     "hoverFontSize" INTEGER DEFAULT 18,
ADD COLUMN     "hoverOffsetX" INTEGER DEFAULT 0,
ADD COLUMN     "hoverText" TEXT,
ADD COLUMN     "hoverTextEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hoverTextStyle" INTEGER DEFAULT 1,
ADD COLUMN     "triangleAlpha1" INTEGER DEFAULT 100,
ADD COLUMN     "triangleAlpha2" INTEGER DEFAULT 100,
ADD COLUMN     "triangleAngle" INTEGER DEFAULT 45,
ADD COLUMN     "triangleColor1" TEXT DEFAULT '#4ecdc4',
ADD COLUMN     "triangleColor2" TEXT DEFAULT '#6a82fb',
ADD COLUMN     "triangleEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "triangleGradientType" TEXT DEFAULT 'solid',
ADD COLUMN     "triangleHeight" INTEGER DEFAULT 200,
ADD COLUMN     "triangleImageOpacity" INTEGER DEFAULT 100,
ADD COLUMN     "triangleImagePos" TEXT DEFAULT 'center',
ADD COLUMN     "triangleImageSize" TEXT DEFAULT 'cover',
ADD COLUMN     "triangleImageUrl" TEXT,
ADD COLUMN     "triangleShape" TEXT DEFAULT 'classic',
ADD COLUMN     "triangleSide" TEXT,
ADD COLUMN     "triangleTargetId" TEXT;
